// <auto-generated />
using System;
using FuelManagementSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelManagementSystem.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250606222525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelManagementSystem.Models.ColumnEquipment", b =>
                {
                    b.Property<int>("ID_ColumnEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ColumnEquipment"));

                    b.Property<int>("ID_Column")
                        .HasColumnType("int");

                    b.Property<int>("ID_Equipment")
                        .HasColumnType("int");

                    b.HasKey("ID_ColumnEquipment");

                    b.HasIndex("ID_Column");

                    b.HasIndex("ID_Equipment");

                    b.ToTable("ColumnEquipments");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.ColumnRepair", b =>
                {
                    b.Property<int>("ID_ColumnRepair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ColumnRepair"));

                    b.Property<int>("ID_Column")
                        .HasColumnType("int");

                    b.Property<int>("ID_Repair")
                        .HasColumnType("int");

                    b.HasKey("ID_ColumnRepair");

                    b.HasIndex("ID_Column");

                    b.HasIndex("ID_Repair");

                    b.ToTable("ColumnRepairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Equipment", b =>
                {
                    b.Property<int>("ID_Equipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Equipment"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Column")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Equipment");

                    b.HasIndex("ID_Column");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.EquipmentRepair", b =>
                {
                    b.Property<int>("ID_EquipmentRepair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_EquipmentRepair"));

                    b.Property<int>("ID_Equipment")
                        .HasColumnType("int");

                    b.Property<int>("ID_Repair")
                        .HasColumnType("int");

                    b.HasKey("ID_EquipmentRepair");

                    b.HasIndex("ID_Equipment");

                    b.HasIndex("ID_Repair");

                    b.ToTable("EquipmentRepairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Fuel", b =>
                {
                    b.Property<int>("ID_Fuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Fuel"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Fuel");

                    b.ToTable("Fuels");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.FuelColumn", b =>
                {
                    b.Property<int>("ID_Column")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Column"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NozzleCount")
                        .HasColumnType("int");

                    b.HasKey("ID_Column");

                    b.ToTable("FuelColumns");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Nozzle", b =>
                {
                    b.Property<int>("ID_Nozzle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Nozzle"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID_Column")
                        .HasColumnType("int");

                    b.Property<int>("ID_Fuel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID_Nozzle");

                    b.HasIndex("ID_Column");

                    b.HasIndex("ID_Fuel");

                    b.ToTable("Nozzles");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.NozzleRepair", b =>
                {
                    b.Property<int>("ID_NozzleRepair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NozzleRepair"));

                    b.Property<int>("ID_Nozzle")
                        .HasColumnType("int");

                    b.Property<int>("ID_Repair")
                        .HasColumnType("int");

                    b.HasKey("ID_NozzleRepair");

                    b.HasIndex("ID_Nozzle");

                    b.HasIndex("ID_Repair");

                    b.ToTable("NozzleRepairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Repair", b =>
                {
                    b.Property<int>("ID_Repair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Repair"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Repairer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Repair");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.ColumnEquipment", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.FuelColumn", "FuelColumn")
                        .WithMany("ColumnEquipments")
                        .HasForeignKey("ID_Column")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSystem.Models.Equipment", "Equipment")
                        .WithMany("ColumnEquipments")
                        .HasForeignKey("ID_Equipment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("FuelColumn");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.ColumnRepair", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.FuelColumn", "FuelColumn")
                        .WithMany("ColumnRepairs")
                        .HasForeignKey("ID_Column")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSystem.Models.Repair", "Repair")
                        .WithMany("ColumnRepairs")
                        .HasForeignKey("ID_Repair")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelColumn");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Equipment", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.FuelColumn", "FuelColumn")
                        .WithMany()
                        .HasForeignKey("ID_Column");

                    b.Navigation("FuelColumn");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.EquipmentRepair", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.Equipment", "Equipment")
                        .WithMany("EquipmentRepairs")
                        .HasForeignKey("ID_Equipment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSystem.Models.Repair", "Repair")
                        .WithMany("EquipmentRepairs")
                        .HasForeignKey("ID_Repair")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Nozzle", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.FuelColumn", "FuelColumn")
                        .WithMany("Nozzles")
                        .HasForeignKey("ID_Column")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSystem.Models.Fuel", "Fuel")
                        .WithMany("Nozzles")
                        .HasForeignKey("ID_Fuel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("FuelColumn");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.NozzleRepair", b =>
                {
                    b.HasOne("FuelManagementSystem.Models.Nozzle", "Nozzle")
                        .WithMany("NozzleRepairs")
                        .HasForeignKey("ID_Nozzle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelManagementSystem.Models.Repair", "Repair")
                        .WithMany("NozzleRepairs")
                        .HasForeignKey("ID_Repair")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Equipment", b =>
                {
                    b.Navigation("ColumnEquipments");

                    b.Navigation("EquipmentRepairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Fuel", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.FuelColumn", b =>
                {
                    b.Navigation("ColumnEquipments");

                    b.Navigation("ColumnRepairs");

                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Nozzle", b =>
                {
                    b.Navigation("NozzleRepairs");
                });

            modelBuilder.Entity("FuelManagementSystem.Models.Repair", b =>
                {
                    b.Navigation("ColumnRepairs");

                    b.Navigation("EquipmentRepairs");

                    b.Navigation("NozzleRepairs");
                });
#pragma warning restore 612, 618
        }
    }
}
